### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by waynelapierre** [boennecd/rollRegres#3]
I noticed this package is removed from CRAN. I have used it a lot, is that possible to publish in CRAN again? Thanks.

**Comment by boennecd** [comment]
Thanks for using the package and thanks for letting me know! It is on [CRAN again](https://cran.r-project.org/package=rollRegres).

**Comment by nikosGeography** [comment]
It seems that the package has been removed from CRAN. I'd like to ask if you are planning to republish it again.
